config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  root "stock_info#index"
  get 'stocks', to: 'stock_info#stocks'
  get 'stock', to: 'stock_info#stock'
  mount Sidekiq::Web => "/sidekiq"
end

app/models/ai_response.rb
class AiResponse < ApplicationRecord
  validates_presence_of :stock
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stock_info_controller.rb
class StockInfoController < ApplicationController
  def index
    news = finnhub.market_news('general')
    @news = news[0..8]
  end

  def stocks
    @symbols = stock_symbols
  end

  def stock
    stock = params['symbol']
    @info = finnhub.symbol_search(stock).result.select { |record| record.symbol == stock }.first
    redirect_to(stocks_path, notice: 'Please enter a valid symbol.') if @info.nil?

    @advisor = FinanceAiAdvisor.new(stock)
    @trends = @advisor.trends
    @reddit_score = @advisor.reddit_score
    @twitter_score = @advisor.twitter_score
    @daily_price_diff = @advisor.daily_price_diff
    @weekly_price_diff = @advisor.weekly_price_diff
    @monthly_price_diff = @advisor.monthly_price_diff
    ai_stock = AiResponse.find_by(stock: stock)
    if ai_stock && Date.parse(ai_stock.created_at.to_s) == Date.today
      @message = ai_stock.response
    else
      ai = AiResponse.new(stock: stock)
      ai.response = @advisor.get_opinion.dig('choices', 0, 'message', 'content')
      ai.save!
      @message = ai.response
    end
  end

  private

  def finnhub
    @finnhub ||= FinnhubRuby::DefaultApi.new
  end

  def stock_symbols
    @stocks = YAML.load_file('config/stocks.yml')['symbols']
  end

  def redirect_from_bad_request
    flash[:notice] = 'Please enter a valid symbol'
    redirect_to root_path 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stock_info_helper.rb
module StockInfoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body class="bg-dark">
    <%= render 'shared/nav' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "StockApp", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Stocks", stocks_path, class: "nav-link"%>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if current_user %>
        <li class="nav-item btn-l-padding m-2">
          <%= link_to current_user.email, root_path, class: "nav-link" %>
        </li>
        <li class="nav-item btn-l-padding m-2">
          <%= button_to "Logout", destroy_user_session_path, method: :delete , class: "btn btn-secondary" %>
        </li>
        <% else %>
        <li class="nav-item btn-l-padding m-2">
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-secondary" %>
        </li>
        <li class="nav-item btn-l-padding m-2">
          <%= link_to "Log In", new_user_session_path, class: "btn btn-secondary" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/stock_info/index.html.erb
<div class="bg-light rounded pt-5">
  <h1 class="text-center">Recent News</h1>
  <div class="row ms-5">
    <% @news.each do |article| %>
      <div class="col-sm-4 p-2">
        <div class="card" style="width: 18rem;">
          <img src="<%= article.image %>" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= article.headline %></h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <%= link_to("See article",  article.url, class: "btn btn-primary") %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stock_info/stock.html.erb
<div class="container bg-light rounded">
  <h2><%= @info.description %></h2>
  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Trends This Month</h3>
        <p>BUYS: <%= @trends ? @trends.first.buy : 'No data currently' %></p>
        <p>STRONG BUYS: <%= @trends ? @trends.first.strong_buy : 'No data currently'  %></p>
        <p>SELLS: <%= @trends ? @trends.first.sell : 'No data currently'  %></p>
        <p>STRONG BUYS: <%= @trends ? @trends.first.strong_sell : 'No data currently'  %></p>
      </div>
      <div class="col">
        <h3>Recent Social Sentiment</h3>
        <p class="text-center">Sentiment scores range from -1 to 1. 1 being a positive sentiment and -1 being negative sentiment.</p>
        <p>REDDIT SENTIMENT SCORE: <%= @reddit_score %></p>
        <p>TWITTER SENTIMENT SCORE: <%= @twitter_score %></p>
      </div>
    </div>
    <div class="row">
      <h3>Price Data</h3>
      <div class="col">
        <div class="container">
          <p>
            Yesterday's Open <%= "#{Time.at(@daily_price_diff.t.first).strftime('%m/%d/%y')}: $#{@daily_price_diff.o.first}" %><br>
            Today's Open <%= "#{Time.at(@daily_price_diff.t.last).strftime('%m/%d/%y')}: $#{@daily_price_diff.o.last}"  %>
          </p>
        </div>
      </div>
      <div class="col">
        <div class="container">
          <p>
            Last Week's Open <%= "#{Time.at(@weekly_price_diff.t.first).strftime('%m/%d/%y')}: $#{@weekly_price_diff.o.first}" %><br>
            This Week's Open <%= "#{Time.at(@weekly_price_diff.t.last).strftime('%m/%d/%y')}: $#{@weekly_price_diff.o.last}" %>
          </p>
        </div>
      </div>
      <div class="col">
        <div class="container">
          <p>
            Last Month's Open <%= "#{Time.at(@monthly_price_diff.t.first).strftime('%m/%d/%y')}: $#{@monthly_price_diff.o.first}" %><br>
            This Month's Open <%= "#{Time.at(@monthly_price_diff.t.last).strftime('%m/%d/%y')}: $#{@monthly_price_diff.o.last}" %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div>
    <h3>AI Recommendation:</h3>
    <p>
      <%= @message %>
    </p>
  </div>
</div>

app/views/stock_info/stocks.html.erb
<div class="bg-light rounded-pill">
  <div class="container">
    <div class="row text-center">
      <%= form_with url: stock_path, method: :get do |f| %>
        <h4><%= f.label :Stock, class: 'col m-2' %></h4>
        <p>Below is a set list of stocks available to view.</p>
        <%= f.select('symbol', options_for_select(@symbols)) %>
        <%= f.submit 'Get info', class: 'btn btn-primary m-2' %>
      <% end %>
    </div>
  </div>
</div>

<%# <%= form_tag('/stock', method: 'GET') do |form| %>
<%#   <%= select_tag('symbol', options_for_select(@symbols)) %>
<%#   <%= submit_tag 'Get your stock info' %>
<%# <% end %> 